package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"time"
)

type registerFlags struct {
	ControllerURL string
	Token         string
	ConfigFile    string
}

type registerRequest struct {
	RegistrationToken string `json:"registration_token"`
	Hostname          string `json:"hostname"`
	OS                string `json:"os"`
	AgentVersion      string `json:"agent_version"`
}

type registerResponseData struct {
	NodeID         string `json:"node_id"`
	NodeKeyID      string `json:"node_key_id"`
	NodeSecret     string `json:"node_secret"`
	ControllerURL  string `json:"controller_url"`
	HeartbeatInterval int  `json:"heartbeat_interval"`
}

type registerResponse struct {
	Data registerResponseData `json:"data"`
}

func parseRegisterFlags(args []string) registerFlags {
	var f registerFlags
	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "--controller" && i+1 < len(args):
			f.ControllerURL = args[i+1]
			i++
		case len(args[i]) > 13 && args[i][:13] == "--controller=":
			f.ControllerURL = args[i][13:]
		case args[i] == "--token" && i+1 < len(args):
			f.Token = args[i+1]
			i++
		case len(args[i]) > 8 && args[i][:8] == "--token=":
			f.Token = args[i][8:]
		case args[i] == "--config" && i+1 < len(args):
			f.ConfigFile = args[i+1]
			i++
		case len(args[i]) > 9 && args[i][:9] == "--config=":
			f.ConfigFile = args[i][9:]
		}
	}
	return f
}

func doRegister(flags registerFlags) error {
	hostname, err := os.Hostname()
	if err != nil {
		hostname = "unknown"
	}

	reqBody := registerRequest{
		RegistrationToken: flags.Token,
		Hostname:          hostname,
		OS:                "linux",
		AgentVersion:      version,
	}

	jsonBody, err := json.Marshal(reqBody)
	if err != nil {
		return fmt.Errorf("failed to marshal request: %w", err)
	}

	url := flags.ControllerURL + "/api/v1/agent/register"
	fmt.Printf("Registering with %s...\n", flags.ControllerURL)

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Post(url, "application/json", bytes.NewReader(jsonBody))
	if err != nil {
		return fmt.Errorf("failed to connect to controller: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)

	if resp.StatusCode != http.StatusCreated {
		var errResp struct {
			Message string `json:"message"`
		}
		json.Unmarshal(body, &errResp)
		return fmt.Errorf("registration failed (HTTP %d): %s", resp.StatusCode, errResp.Message)
	}

	var regResp registerResponse
	if err := json.Unmarshal(body, &regResp); err != nil {
		return fmt.Errorf("failed to parse response: %w", err)
	}

	// Determine config file path
	configPath := flags.ConfigFile
	if configPath == "" {
		configPath = "/etc/lg-agent/config.yaml"
	}

	// Write config file
	cfgContent := fmt.Sprintf(`# lg-agent configuration
# Generated by registration at %s

node_id: "%s"
node_key_id: "%s"
node_secret: "%s"
controller_url: "%s"
listen_addr: ":8443"
heartbeat_interval: %d
config_file: "%s"
`, time.Now().UTC().Format(time.RFC3339),
		regResp.Data.NodeID,
		regResp.Data.NodeKeyID,
		regResp.Data.NodeSecret,
		regResp.Data.ControllerURL,
		regResp.Data.HeartbeatInterval,
		configPath,
	)

	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	if err := os.WriteFile(configPath, []byte(cfgContent), 0600); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Println()
	fmt.Println("Registration successful!")
	fmt.Printf("  Node ID:      %s\n", regResp.Data.NodeID)
	fmt.Printf("  Key ID:       %s\n", regResp.Data.NodeKeyID)
	fmt.Printf("  Config file:  %s\n", configPath)
	fmt.Println()
	fmt.Println("Credentials have been written to the config file.")
	fmt.Println("Start the agent with: lg-agent serve")
	fmt.Println("Or install as a systemd service.")

	return nil
}
